sms_service:
  worker_count: 1
  peek_count: 10

pgsql:
  dsn: "host=localhost user=postgres password=12345678 dbname=sms_gateway port=5432 sslmode=disable TimeZone=Asia/Tehran"
  migrations_path: "file://migrations/pgsql"

redis:
  address: 127.0.0.1:6379
  password: 12345678

log_level: Debug
