// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AshkanAbd/arvancloud_sms_gateway/internal/sms/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockISmsSender creates a new instance of MockISmsSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISmsSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISmsSender {
	mock := &MockISmsSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockISmsSender is an autogenerated mock type for the ISmsSender type
type MockISmsSender struct {
	mock.Mock
}

type MockISmsSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISmsSender) EXPECT() *MockISmsSender_Expecter {
	return &MockISmsSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockISmsSender
func (_mock *MockISmsSender) Send(ctx context.Context, msg models.Sms) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Sms) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISmsSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockISmsSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - msg models.Sms
func (_e *MockISmsSender_Expecter) Send(ctx interface{}, msg interface{}) *MockISmsSender_Send_Call {
	return &MockISmsSender_Send_Call{Call: _e.mock.On("Send", ctx, msg)}
}

func (_c *MockISmsSender_Send_Call) Run(run func(ctx context.Context, msg models.Sms)) *MockISmsSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Sms
		if args[1] != nil {
			arg1 = args[1].(models.Sms)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISmsSender_Send_Call) Return(err error) *MockISmsSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISmsSender_Send_Call) RunAndReturn(run func(ctx context.Context, msg models.Sms) error) *MockISmsSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
